[package]
name = "analog-test-validator"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-test-validator"
readme = "../README.md"
repository = "https://github.com/analog-labs/analog"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.3"
log = "0.4.14"
analog-client = { path = "../client", version = "=1.9.0" }
analog-core = { path = "../core", version = "=1.9.0" }
analog-gossip = { path = "../gossip", version = "=1.9.0" }
analog-ledger = { path = "../ledger", version = "=1.9.0" }
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-net-utils = { path = "../net-utils", version = "=1.9.0" }
analog-program-test = { path = "../program-test", version = "=1.9.0" }
analog-rpc = { path = "../rpc", version = "=1.9.0" }
analog-runtime = { path = "../runtime", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-streamer = { path = "../streamer", version = "=1.9.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
