[package]
name = "analog-bpf-rust-sanity"
version = "1.9.0"
description = "Analog BPF test program written in Rust"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-bpf-rust-sanity"
edition = "2018"

[features]
test-bpf = []

[dependencies]
solana-program= { path = "../../../../sdk/program", version = "=1.9.0" }

[dev-dependencies]
analog-program-test = { path = "../../../../program-test", version = "=1.9.0" }
analog-sdk = { path = "../../../../sdk", version = "=1.9.0" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
