[package]
name = "analog-storage-proto"
version = "1.9.0"
description = "Analog Storage Protobuf Definitions"
authors = ["Analog Maintainers <maintainers@analog.com>"]
repository = "https://github.com/analog-labs/analog"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-storage-proto"
edition = "2018"

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
prost = "0.9.0"
serde = "1.0.130"
analog-account-decoder = { path = "../account-decoder", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-transaction-status = { path = "../transaction-status", version = "=1.9.0" }

[lib]
crate-type = ["lib"]
name = "analog_storage_proto"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.6.0"
