[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-sys-tuner"
description = "The analog cluster system tuner daemon"
version = "1.9.0"
repository = "https://github.com/analog-labs/analog"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
log = "0.4.14"
libc = "0.2.107"
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-version = { path = "../version", version = "=1.9.0" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.23.0"
sysctl = "0.4.3"

[lib]
name = "analog_sys_tuner"

[[bin]]
name = "analog-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
