[package]
name = "analog-program-runtime"
version = "1.9.0"
description = "Analog program runtime"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-program-runtime"
edition = "2018"

[dependencies]
bincode = "1.3.3"
libc = "0.2.101"
libloading = "0.7.0"
log = "0.4.14"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = { version = "1.0.129", features = ["derive", "rc"] }
analog-frozen-abi = { path = "../frozen-abi", version = "=1.9.0" }
analog-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.0" }
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
thiserror = "1.0"

[lib]
crate-type = ["lib"]
name = "solana_program_runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
