[package]
name = "analog-measure"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-measure"
readme = "../README.md"
repository = "https://github.com/analog-labs/solana"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.14"
analog-sdk = { path = "../sdk", version = "=1.9.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
