[package]
authors = ["Analog Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "analog-log-analyzer"
description = "The analog cluster network analysis tool"
version = "1.9.0"
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
byte-unit = "4.0.13"
clap = "2.33.1"
serde = "1.0.130"
serde_json = "1.0.69"
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-version = { path = "../version", version = "=1.9.0" }

[[bin]]
name = "analog-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
