[package]
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "analog-store-tool"
description = "Tool to inspect append vecs"
version = "1.9.0"
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
log = { version = "0.4.14" }
analog-logger = { path = "../../logger", version = "=1.9.0" }
analog-version = { path = "../../version", version = "=1.9.0" }
analog-runtime = { path = "..", version = "=1.9.0" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
