[package]
name = "analog-logger"
version = "1.9.0"
description = "Analog Logger"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-logger"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.14"

[lib]
name = "analog_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
