[package]
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
edition = "2018"
name = "analog-poh-bench"
version = "1.9.0"
repository = "https://github.com/analog-labs/analog"
license = "Apache-2.0"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-poh-bench"

[dependencies]
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-entry = { path = "../entry", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-measure = { path = "../measure", version = "=1.9.0" }
analog-version = { path = "../version", version = "=1.9.0" }
analog-perf = { path = "../perf", version = "=1.9.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
