[package]
name = "analog-upload-perf"
version = "1.9.0"
description = "Metrics Upload Utility"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog-labs/analog"
license = "Apache-2.0"
edition = "2018"
homepage = "https://analog.com/"
publish = false

[dependencies]
serde_json = "1.0.69"
analog-metrics = { path = "../metrics", version = "=1.9.0" }

[[bin]]
name = "analog-upload-perf"
path = "src/upload-perf.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
