[package]
name = "analog-rpc"
version = "1.9.0"
description = "Analog RPC"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-rpc"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
crossbeam-channel = "0.5"
dashmap = "4.0.2"
itertools = "0.10.1"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-http-server = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpc-ws-server = "18.0.0"
libc = "0.2.107"
log = "0.4.14"
rayon = "1.5.1"
regex = "1.5.4"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.69"
soketto = "0.7"
analog-account-decoder = { path = "../account-decoder", version = "=1.9.0" }
analog-client = { path = "../client", version = "=1.9.0" }
analog-entry = { path = "../entry", version = "=1.9.0" }
analog-faucet = { path = "../faucet", version = "=1.9.0" }
analog-gossip = { path = "../gossip", version = "=1.9.0" }
analog-ledger = { path = "../ledger", version = "=1.9.0" }
analog-measure = { path = "../measure", version = "=1.9.0" }
analog-metrics = { path = "../metrics", version = "=1.9.0" }
analog-perf = { path = "../perf", version = "=1.9.0" }
analog-poh = { path = "../poh", version = "=1.9.0" }
analog-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.0" }
analog-runtime = { path = "../runtime", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.0" }
analog-streamer = { path = "../streamer", version = "=1.9.0" }
analog-storage-bigtable = { path = "../storage-bigtable", version = "=1.9.0" }
analog-transaction-status = { path = "../transaction-status", version = "=1.9.0" }
analog-version = { path = "../version", version = "=1.9.0" }
analog-vote-program = { path = "../programs/vote", version = "=1.9.0" }
spl-token-v2-0 = { package = "spl-token", version = "=3.2.0", features = ["no-entrypoint"] }
stream-cancel = "0.8.1"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec", "compat"] }

[dev-dependencies]
serial_test = "0.5.1"
analog-net-utils = { path = "../net-utils", version = "=1.9.0" }
analog-stake-program = { path = "../programs/stake", version = "=1.9.0" }
symlink = "0.1.0"

[lib]
crate-type = ["lib"]
name = "analog_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
