[package]
name = "analog-notifier"
version = "1.9.0"
description = "Analog Notifier"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-notifier"
edition = "2018"

[dependencies]
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0"

[lib]
name = "analog_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
